### ISSUE TITLE
recording videos or demo videos generation

### ISSUE THREAD

**Issue by J-X-Chen** [TongZhangTHU/sgr#3]
Knowing that PerAct can generate video results, may I ask whether you have written the code related to simulation video outputs like PerAct.

**Comment by TongZhangTHU** [comment]
Yes, you can add `cinematic_recorder.enabled=True` (https://github.com/TongZhangTHU/sgr/blob/main/conf/eval.yaml#L27) when run evaluation (https://github.com/TongZhangTHU/sgr/blob/main/README.md?plain=1#L156) to generate video results.

**Comment by J-X-Chen** [comment]
Thank you!
